# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# Apply AWS openshift security group rules
---
- name: OPENSHIFT OVERLAY | discovering {{ application }} instances
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}"
      "tag:Application": "{{ application }}"
      "tag:Cluster": "{{ cluster | default ('none') }}"
      "tag:Dataflow": "{{ dataflow | default ('none') }}"
  register: all_openshift_nodes
  when: cloud == 'aws'

# construct list of all interfaces attached to postgresql nodes
- set_fact:
    openshift_interfaces: "{{ all_openshift_nodes.instances | map(attribute='network_interfaces') | list }}"
  when: all_openshift_nodes.instances | length > 0
  
# apply openshift rules
- name: OPENSHIFT OVERLAY | applying {{ application }} security rules to interface 1
  ec2_eni:
    region: "{{ region }}"
    eni_id: "{{ item.network_interface_id }}"
    security_groups:
      - "{{ sg_openshift.group_id }}"
  with_items: "{{ openshift_interfaces }}"
  when: item.attachment.device_index == 1