# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# discover AWS inventory
---
- name: OPENSHIFT OVERLAY | setting key_path
  set_fact: key_path="{{ ansible_env.PWD }}"
  when: key_path is not defined

- name: OPENSHIFT OVERLAY | discovering {{ application }}
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}"
      "tag:Application": openshift
      "tag:Cluster": "{{ cluster | default ('a') }}"
      "tag:Dataflow": "{{ dataflow | default ('none') }}"
  register: openshift_instances
  when: cloud == 'aws'

- name: OPENSHIFT OVERLAY | building openshift host group
  add_host: hostname="{{ item }}" groupname=openshift ansible_user="{{ user }}" ansible_ssh_private_key_file="{{ key_path }}/{{ cloud }}-{{ region }}-{{ project }}-{{ application }}-{{ domain }}-private-key.pem"
  with_items: "{{ openshift_instances.instances | map (attribute='private_ip_address') | list }}"
  when:
    - cloud == 'aws'
    - openshift_instances is defined
    - openshift_instances.instances | length > 0
